#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("HuffmanHenryCase1.Resource", IsApplication=true)]

namespace HuffmanHenryCase1
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050015
			public const int btnBack = 2131034133;
			
			// aapt resource value: 0x7f05001b
			public const int btnCRUD = 2131034139;
			
			// aapt resource value: 0x7f050005
			public const int btnCreate = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int btnDelete = 2131034119;
			
			// aapt resource value: 0x7f050003
			public const int btnFindId = 2131034115;
			
			// aapt resource value: 0x7f050018
			public const int btnGenerate = 2131034136;
			
			// aapt resource value: 0x7f050002
			public const int btnNext = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int btnPrevious = 2131034113;
			
			// aapt resource value: 0x7f05001c
			public const int btnStatistics = 2131034140;
			
			// aapt resource value: 0x7f050006
			public const int btnUpdate = 2131034118;
			
			// aapt resource value: 0x7f050009
			public const int etEmployeeId = 2131034121;
			
			// aapt resource value: 0x7f050017
			public const int etEmployeePrompt = 2131034135;
			
			// aapt resource value: 0x7f05000b
			public const int etFirstName = 2131034123;
			
			// aapt resource value: 0x7f05000f
			public const int etHourlyWage = 2131034127;
			
			// aapt resource value: 0x7f050011
			public const int etHoursWorked = 2131034129;
			
			// aapt resource value: 0x7f05000d
			public const int etLastName = 2131034125;
			
			// aapt resource value: 0x7f050013
			public const int etTotalPayroll = 2131034131;
			
			// aapt resource value: 0x7f050000
			public const int linearLayout1 = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int linearLayout2 = 2131034116;
			
			// aapt resource value: 0x7f050014
			public const int tvCRUDError = 2131034132;
			
			// aapt resource value: 0x7f050008
			public const int tvEmployeeId = 2131034120;
			
			// aapt resource value: 0x7f050016
			public const int tvEmployeePrompt = 2131034134;
			
			// aapt resource value: 0x7f050019
			public const int tvError = 2131034137;
			
			// aapt resource value: 0x7f05000a
			public const int tvFirstName = 2131034122;
			
			// aapt resource value: 0x7f05000e
			public const int tvHourlyWage = 2131034126;
			
			// aapt resource value: 0x7f050010
			public const int tvHoursWorked = 2131034128;
			
			// aapt resource value: 0x7f05000c
			public const int tvLastName = 2131034124;
			
			// aapt resource value: 0x7f05001a
			public const int tvOperation = 2131034138;
			
			// aapt resource value: 0x7f05001d
			public const int tvTest = 2131034141;
			
			// aapt resource value: 0x7f050012
			public const int tvTotalPayroll = 2131034130;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CRUD = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Operations = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
